const dashboardRoutes = require("./dashboard.routes")
const productsRoutes = require("./products.routes")
const productsCategoryRoutes = require("./products-category.routes")
const BlogsCategoryRoutes = require("./blogs-category.routes")
const trashRoutes = require("./trash.routes")
const uploadRoutes = require("./uploadImage.routes")
const roleRoutes = require("./role.routes")
const accountRoutes = require("./accounts.routes")
const authRoutes = require("./auth.routes")
const myAccountRoutes = require("./my-account.routes")
const systemConfig = require("../../Config/systems")

const authMiddleware = require("../../Middlewares/Admin/auth.middleware")
module.exports = (app)=>{
    
    app.use(systemConfig.prefixAdmin+'/dashboard',authMiddleware.requireAuthClient,dashboardRoutes)
    app.use(systemConfig.prefixAdmin+'/products',authMiddleware.requireAuthClient,productsRoutes)
    app.use(systemConfig.prefixAdmin+'/products-category',authMiddleware.requireAuthClient,productsCategoryRoutes)
    app.use(systemConfig.prefixAdmin+'/blogs-category',authMiddleware.requireAuthClient,BlogsCategoryRoutes)
    app.use(systemConfig.prefixAdmin+'/trash',authMiddleware.requireAuthClient,trashRoutes)
    app.use(systemConfig.prefixAdmin+'/upload',authMiddleware.requireAuthClient,uploadRoutes)
    app.use(systemConfig.prefixAdmin+'/roles',authMiddleware.requireAuthClient,roleRoutes)
    app.use(systemConfig.prefixAdmin+'/accounts',authMiddleware.requireAuthClient,accountRoutes)
    app.use(systemConfig.prefixAdmin+'/my-account',authMiddleware.requireAuthClient,myAccountRoutes)
    app.use(systemConfig.prefixAdmin+'/auth',authRoutes)
}